#!/usr/bin/env python3
"""Convergence audit for named run folders generated by simulate_spectrum.py."""
import argparse,json,hashlib,sys
from pathlib import Path
import numpy as np
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'python'))
from convergence import compare
from surface_storage import atomic_json
p=argparse.ArgumentParser();p.add_argument('--plan',required=True);p.add_argument('--out-root',required=True);p.add_argument('--tag',default='production');a=p.parse_args()
plan_path=Path(a.plan);plan=json.loads(plan_path.read_text());out=Path(a.out_root);found={};rows=[]
out.mkdir(parents=True,exist_ok=True)
def spectrum_file(folder,name='spectrum.npz'):
    file=folder/name
    if not file.exists() and name=='spectrum.npz' and (folder/'observables.json').exists():
        file=folder/json.loads((folder/'observables.json').read_text())['artifacts']['spectrum']
    return file
for case in plan['cases']:
    expected=json.loads((plan_path.parent/(case+'.json')).read_text());matches=[]
    candidates=list(out.glob(case+('__'+a.tag if a.tag else '')+'__*'))
    if (out/case).is_dir():candidates.append(out/case)
    for folder in candidates:
        if not (folder/'run.json').exists():continue
        meta=json.loads((folder/'run.json').read_text())
        template=json.loads((folder/'input_template.json').read_text()) if (folder/'input_template.json').exists() else meta['config']
        if meta.get('complete') and spectrum_file(folder).exists() and template==expected:matches.append(folder)
    if len(matches)>1:raise ValueError(f'{case}: multiple complete effective inputs; choose a separate tag/output root')
    if matches:found[case]=matches[0]
for pair in plan.get('pairs',[])+plan.get('extraction_pairs',[]):
    row=dict(pair);first=found.get(pair['reference']);second=found.get(pair['refinement'])
    fa=spectrum_file(first,pair.get('reference_file','spectrum.npz')) if first else None
    fb=spectrum_file(second,pair.get('refinement_file','spectrum.npz')) if second else None
    if fa is None or fb is None or not fa.exists() or not fb.exists():row['status']='pending'
    else:
        kernels=[]
        for folder in [first,second]:
            layout=folder/'surface_online/layout.json'
            kernels.append(json.loads(layout.read_text())['recipe']['kernel'] if layout.exists() else None)
        if kernels[0]!=kernels[1]:raise ValueError('convergence cases mix numerical kernels; rerun with one recorded snapshot')
        spectra=[]
        for folder,file in [(first,fa),(second,fb)]:
            meta=json.loads((folder/'run.json').read_text());data=np.load(file)
            if str(data['source_signature'])!=meta['signature']:raise ValueError('stale spectrum configuration')
            spectra.append(data)
        criteria=dict(pair.get('acceptance',plan['acceptance']))
        if pair.get('allow_ionic_extension'):criteria['allow_ionic_extension']=True
        windows=pair.get('energy_windows',criteria.get('energy_windows',[None]))
        row['windows']=[compare(*spectra,criteria,window) for window in windows]
        row['status']='passed' if all(w['status']=='passed' for w in row['windows']) else 'failed'
    rows.append(row)
result={'cases_found':{k:str(v) for k,v in found.items()},'comparisons':rows,'all_defined_gates_passed':bool(rows and len(found)==len(plan['cases']) and all(r['status']=='passed' for r in rows)),
        'scope':'Only the given plan and matching input templates; task names do not certify convergence.'}
atomic_json(out/'campaign_acceptance.json',result)
for row in rows:print(row['status'].upper(),row.get('axis',row['refinement']))
